### ISSUE TITLE
Optimize build times

### ISSUE THREAD

**Issue by thebongy** [csivitu/ctfup#2]
Build times can be optimised by not rebuilding unchanged containers. Maybe we can use `git diff` or something to only deploy changed containers

Not sure if this is well fit to be a part of `ctfup` tho, maybe ctfup can just take another option, like `--build-only=<challenge names>`, to filter only some challenges to be built/deployed.

**Comment by roerohan** [comment]
# --diff \<commit-hash\> to optimize builds

> Optimization of build times.

Build times have been optimized with the help of the `--diff` or `-d` flag. You can pass a commit hash to the `--diff` flag in the following manner:

```bash
ctfup -c ctfup.yml -d <commit-hash> .
```

This will only deploy the challenges that have been modified since that commit hash, and not all the challenges, optimizing build times to a huge extent.

## Sample usage in github actions

```yml
...
      - name: Deploy
        run: |
          echo ${{ env.COMMITHASH }}
          ctfup -c ctfup.yml -d ${{ env.COMMITHASH }} .
        env:
          COMMITHASH: $(git rev-list -n 1 latest)
  
      - run: |
          git config --global user.email "roerohan@gmail.com"
          git config --global user.name "roerohan"
          git tag -fa latest -m "feat:Update latest tag"
          git push -f origin latest
```

Here, `latest` is the tag which stores the latest code prior to `this` push. So, it will deploy only those challenges that are added/modified in `this` push. Then it will update the `latest` tag.
